#!/bin/bash

set -e

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

cd ${ROOT}
mkdir -p ${ROOT}/_build

bundler install --path _build/ruby

git submodule update --init --recursive

cd ${ROOT}/_build

export CC=clang
export CXX=clang++
cmake ${ROOT} -G Ninja

cd ${ROOT}

cmake --build _build
cmake --build _build --target format

${ROOT}/_build/source/features/wire-server &
cd ${ROOT}/source

#bundler exec cucumber -p done
bundler exec cucumber -p wip

